### ISSUE TITLE
any one can help me

### ISSUE THREAD

**Issue by alihashemi7272** [omelchert/optfrog#1]
respectfully,
 
I have a problem to use this code for my structure.
i have used split step method for solving nonlinear schrodinger equation written by dudley 2010 in Matlab.

I convert the complex time-domain at last raw to npz files. then run the python codes but the output right figure  has stopped at zero frequency. the input wavelength for my structure is about 6 micrometer. there is a mismatch frequency between AT Matlab output and Et input python codes. what is the difference between them? 

So, I would ask you please guide me the implementation & figure drawing codes of spectrogram, if may. I'll be gratitude if you consider and reply me.

I'am eagerly seeking your response.

Thanks in advance.
Sincerely yours
Ali
![fig_vanillaFrog_ESM_sigma140 000pcf1200-new](https://user-images.githubusercontent.com/59265963/72525439-68487a00-3879-11ea-9908-cb79375b6860.png)

**Comment by omelchert** [comment]
Dear Ali,

the optfrog utility is designed to work for the analytic signal
related to the real optical field. This involves the actual optical
angular frequency in terms of an unidirectional propagation approach
for which negative frequencies are omitted.

In contrast, the nonlinear Schroedinger equation (NSE) introduces the concept
of a carrier frequency and involves a frequency detuning relative to that
carrier frequency.

So, by using the optfrog-utility in a naive way, you omit the negative
frequencies. This is correct for the propagation method for the analytic
signal, while is does not directly carry over to the NSE (so, your negative
frequency detunings appear to be cut off).

There are several possibilities to proceed:

(1) shift and zero-pad your signal to represent the actual optical  
frequency and use
the optfrog utility as is, or

(2) send me your data that produced the figure you enclosed (i.e. your  
input data
to the optfrog utility and script you used to produced the figure). I have a
concise python script that generates spectrograms for data generated using
a NSE employing frequency detunings. However, I am quite busy and it  
might take
until monday to respond.

Best,
O


Quoting alihashemi7272 <notifications@github.com>:
